name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: '23.0'
          elixir-version: '1.10.4'
      - run: git submodule update --init --recursive
      - run: sudo apt install libevent-dev
      - run: mix deps.get
      - run: mix test
